import { type Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Providers } from "./providers";
import { Sidebar } from "@/components/Sidebar";
import cn from "classnames";
import { Button } from "@/components/Button";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const main = <main className="flex-1">{children}</main>;

  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Providers>
            <div className="">
              <Sidebar
                classname={cn(
                  `fixed md:w-72 xl:w-108 px-2 bg-frost-white h-dvh`,
                )}
              />
              <div className={`flex h-dvh flex-col ml-0 md:ml-72 xl:ml-108 `}>
                <Header />
                {main}
              </div>
            </div>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
